/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { GroupPredict__factory } from "./GroupPredict__factory";
export { MultipleChoices__factory } from "./MultipleChoices__factory";
