/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  EventStorage,
  EventStorageInterface,
} from "../../../contracts/Event.sol/EventStorage";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "events",
    outputs: [
      {
        internalType: "uint256",
        name: "startTime",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "deadlineTime",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "endTime",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "resultIndex",
        type: "uint256",
      },
      {
        internalType: "enum EDataTypes.EventStatus",
        name: "status",
        type: "uint8",
      },
      {
        internalType: "address",
        name: "helperAddress",
        type: "address",
      },
      {
        internalType: "address",
        name: "creator",
        type: "address",
      },
      {
        internalType: "string",
        name: "_datas",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "pro",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "isBlock",
        type: "bool",
      },
      {
        internalType: "uint256",
        name: "finalTime",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "nEvents",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506102f0806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c80630b7914301461003b578063bca321e51461006e575b600080fd5b61004e610049366004610189565b610085565b6040516100659b9a999897969594939291906101ec565b60405180910390f35b61007760015481565b604051908152602001610065565b6000602081905290815260409020805460018201546002830154600384015460048501546005860154600787018054969795969495939460ff84169461010090940473ffffffffffffffffffffffffffffffffffffffff9081169493169291906100ee906102a8565b80601f016020809104026020016040519081016040528092919081815260200182805461011a906102a8565b80156101675780601f1061013c57610100808354040283529160200191610167565b820191906000526020600020905b81548152906001019060200180831161014a57829003601f168201915b5050505060088301546009840154600a909401549293909260ff90911691508b565b60006020828403121561019a578081fd5b5035919050565b60008151808452815b818110156101c6576020818501810151868301820152016101aa565b818111156101d75782602083870101525b50601f01601f19169290920160200192915050565b60006101608d83528c60208401528b60408401528a606084015260028a1061022257634e487b7160e01b82526021600452602482fd5b89608084015261024a60a084018a73ffffffffffffffffffffffffffffffffffffffff169052565b73ffffffffffffffffffffffffffffffffffffffff881660c08401528060e0840152610278818401886101a1565b9150508461010083015261029161012083018515159052565b826101408301529c9b505050505050505050505050565b600181811c908216806102bc57607f821691505b602082108114156102dd57634e487b7160e01b600052602260045260246000fd5b5091905056fea164736f6c6343000804000a";

type EventStorageConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: EventStorageConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class EventStorage__factory extends ContractFactory {
  constructor(...args: EventStorageConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<EventStorage> {
    return super.deploy(overrides || {}) as Promise<EventStorage>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): EventStorage {
    return super.attach(address) as EventStorage;
  }
  override connect(signer: Signer): EventStorage__factory {
    return super.connect(signer) as EventStorage__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): EventStorageInterface {
    return new utils.Interface(_abi) as EventStorageInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): EventStorage {
    return new Contract(address, _abi, signerOrProvider) as EventStorage;
  }
}
