/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  EventStorage,
  EventStorageInterface,
} from "../../../contracts/Event.sol/EventStorage";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "events",
    outputs: [
      {
        internalType: "uint256",
        name: "startTime",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "deadlineTime",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "endTime",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "resultIndex",
        type: "uint256",
      },
      {
        internalType: "enum EDataTypes.EventStatus",
        name: "status",
        type: "uint8",
      },
      {
        internalType: "address",
        name: "helperAddress",
        type: "address",
      },
      {
        internalType: "address",
        name: "creator",
        type: "address",
      },
      {
        internalType: "string",
        name: "_datas",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "pro",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "isBlock",
        type: "bool",
      },
      {
        internalType: "uint256",
        name: "finalTime",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "claimTime",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "affiliate",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "nEvents",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610317806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c80630b7914301461003b578063bca321e514610070575b600080fd5b61004e610049366004610198565b610087565b6040516100679d9c9b9a999897969594939291906101fb565b60405180910390f35b61007960015481565b604051908152602001610067565b6000602081905290815260409020805460018201546002830154600384015460048501546005860154600787018054969795969495939460ff84169461010090940473ffffffffffffffffffffffffffffffffffffffff9081169493169291906100f0906102cf565b80601f016020809104026020016040519081016040528092919081815260200182805461011c906102cf565b80156101695780601f1061013e57610100808354040283529160200191610169565b820191906000526020600020905b81548152906001019060200180831161014c57829003601f168201915b50505060088401546009850154600a860154600b870154600c909701549596929560ff9283169550909350168d565b6000602082840312156101a9578081fd5b5035919050565b60008151808452815b818110156101d5576020818501810151868301820152016101b9565b818111156101e65782602083870101525b50601f01601f19169290920160200192915050565b60006101a08f83528e60208401528d60408401528c606084015260028c1061023157634e487b7160e01b82526021600452602482fd5b8b608084015261025960a084018c73ffffffffffffffffffffffffffffffffffffffff169052565b73ffffffffffffffffffffffffffffffffffffffff8a1660c08401528060e08401526102878184018a6101b0565b915050866101008301526102a061012083018715159052565b84610140830152836101608301526102bd61018083018415159052565b9e9d5050505050505050505050505050565b600181811c908216806102e357607f821691505b6020821081141561030457634e487b7160e01b600052602260045260246000fd5b5091905056fea164736f6c6343000804000a";

type EventStorageConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: EventStorageConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class EventStorage__factory extends ContractFactory {
  constructor(...args: EventStorageConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<EventStorage> {
    return super.deploy(overrides || {}) as Promise<EventStorage>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): EventStorage {
    return super.attach(address) as EventStorage;
  }
  override connect(signer: Signer): EventStorage__factory {
    return super.connect(signer) as EventStorage__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): EventStorageInterface {
    return new utils.Interface(_abi) as EventStorageInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): EventStorage {
    return new Contract(address, _abi, signerOrProvider) as EventStorage;
  }
}
