/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Event__factory } from "./Event__factory";
export { EventStorage__factory } from "./EventStorage__factory";
