/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../common";

export declare namespace MDataTypes {
  export type ScoreStruct = {
    firstTeam: BigNumberish;
    secondTeam: BigNumberish;
  };

  export type ScoreStructOutput = [BigNumber, BigNumber] & {
    firstTeam: BigNumber;
    secondTeam: BigNumber;
  };

  export type MatchStruct = {
    description: BytesLike;
    startTime: BigNumberish;
    endTime: BigNumberish;
    score: MDataTypes.ScoreStruct;
    status: BigNumberish;
    sToken: string;
    sTotal: BigNumberish;
  };

  export type MatchStructOutput = [
    string,
    BigNumber,
    BigNumber,
    MDataTypes.ScoreStructOutput,
    number,
    string,
    BigNumber
  ] & {
    description: string;
    startTime: BigNumber;
    endTime: BigNumber;
    score: MDataTypes.ScoreStructOutput;
    status: number;
    sToken: string;
    sTotal: BigNumber;
  };
}

export interface MIMatchInterface extends utils.Interface {
  functions: {
    "info(uint256)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "info"): FunctionFragment;

  encodeFunctionData(functionFragment: "info", values: [BigNumberish]): string;

  decodeFunctionResult(functionFragment: "info", data: BytesLike): Result;

  events: {};
}

export interface MIMatch extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MIMatchInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    info(
      _matchId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [MDataTypes.MatchStructOutput] & { _match: MDataTypes.MatchStructOutput }
    >;
  };

  info(
    _matchId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<MDataTypes.MatchStructOutput>;

  callStatic: {
    info(
      _matchId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<MDataTypes.MatchStructOutput>;
  };

  filters: {};

  estimateGas: {
    info(_matchId: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    info(
      _matchId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
