/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../../common";

export declare namespace GDataTypes {
  export type EventStruct = {
    description: BytesLike;
    startTime: BigNumberish;
    endTime: BigNumberish;
    result: string;
    status: BigNumberish;
    sToken: string;
    sTotal: BigNumberish;
  };

  export type EventStructOutput = [
    string,
    BigNumber,
    BigNumber,
    string,
    number,
    string,
    BigNumber
  ] & {
    description: string;
    startTime: BigNumber;
    endTime: BigNumber;
    result: string;
    status: number;
    sToken: string;
    sTotal: BigNumber;
  };
}

export interface GroupEventInterface extends utils.Interface {
  functions: {
    "createEventes(bytes32[],uint256[],uint256[],address[],uint256[])": FunctionFragment;
    "eventes(uint256)": FunctionFragment;
    "info(uint256)": FunctionFragment;
    "initialize()": FunctionFragment;
    "nEventes()": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setAdminPermission(address,bool)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "updateEventResults(uint256[],string[])": FunctionFragment;
    "updateEventStatuses(uint256[],uint8[])": FunctionFragment;
    "updateSToken(uint256[],address[],uint256[])": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "createEventes"
      | "eventes"
      | "info"
      | "initialize"
      | "nEventes"
      | "owner"
      | "renounceOwnership"
      | "setAdminPermission"
      | "transferOwnership"
      | "updateEventResults"
      | "updateEventStatuses"
      | "updateSToken"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createEventes",
    values: [
      BytesLike[],
      BigNumberish[],
      BigNumberish[],
      string[],
      BigNumberish[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "eventes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "info", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "nEventes", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAdminPermission",
    values: [string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateEventResults",
    values: [BigNumberish[], string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "updateEventStatuses",
    values: [BigNumberish[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "updateSToken",
    values: [BigNumberish[], string[], BigNumberish[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "createEventes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "eventes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "info", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nEventes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAdminPermission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateEventResults",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateEventStatuses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateSToken",
    data: BytesLike
  ): Result;

  events: {
    "EventCreated(uint256,bytes32,uint256,uint256,address,uint256)": EventFragment;
    "EventResultUpdated(address,uint256,string)": EventFragment;
    "EventStatusUpdated(address,uint256,uint8)": EventFragment;
    "Initialized(uint8)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "EventCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EventResultUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EventStatusUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export interface EventCreatedEventObject {
  idx: BigNumber;
  descriptions: string;
  startTime: BigNumber;
  endTime: BigNumber;
  sToken: string;
  sTotal: BigNumber;
}
export type EventCreatedEvent = TypedEvent<
  [BigNumber, string, BigNumber, BigNumber, string, BigNumber],
  EventCreatedEventObject
>;

export type EventCreatedEventFilter = TypedEventFilter<EventCreatedEvent>;

export interface EventResultUpdatedEventObject {
  caller: string;
  eventId: BigNumber;
  result: string;
}
export type EventResultUpdatedEvent = TypedEvent<
  [string, BigNumber, string],
  EventResultUpdatedEventObject
>;

export type EventResultUpdatedEventFilter =
  TypedEventFilter<EventResultUpdatedEvent>;

export interface EventStatusUpdatedEventObject {
  caller: string;
  eventId: BigNumber;
  status: number;
}
export type EventStatusUpdatedEvent = TypedEvent<
  [string, BigNumber, number],
  EventStatusUpdatedEventObject
>;

export type EventStatusUpdatedEventFilter =
  TypedEventFilter<EventStatusUpdatedEvent>;

export interface InitializedEventObject {
  version: number;
}
export type InitializedEvent = TypedEvent<[number], InitializedEventObject>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface GroupEvent extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: GroupEventInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    createEventes(
      _descriptions: BytesLike[],
      _startTimes: BigNumberish[],
      _endTimes: BigNumberish[],
      _sToken: string[],
      _sTotal: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    eventes(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber, string, number, string, BigNumber] & {
        description: string;
        startTime: BigNumber;
        endTime: BigNumber;
        result: string;
        status: number;
        sToken: string;
        sTotal: BigNumber;
      }
    >;

    info(
      _eventId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [GDataTypes.EventStructOutput] & { _event: GDataTypes.EventStructOutput }
    >;

    initialize(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    nEventes(overrides?: CallOverrides): Promise<[BigNumber]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setAdminPermission(
      _admin: string,
      _status: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateEventResults(
      _eventIds: BigNumberish[],
      _results: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateEventStatuses(
      _eventIds: BigNumberish[],
      _status: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateSToken(
      _eventIds: BigNumberish[],
      _sToken: string[],
      _sTotal: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  createEventes(
    _descriptions: BytesLike[],
    _startTimes: BigNumberish[],
    _endTimes: BigNumberish[],
    _sToken: string[],
    _sTotal: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  eventes(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, BigNumber, string, number, string, BigNumber] & {
      description: string;
      startTime: BigNumber;
      endTime: BigNumber;
      result: string;
      status: number;
      sToken: string;
      sTotal: BigNumber;
    }
  >;

  info(
    _eventId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<GDataTypes.EventStructOutput>;

  initialize(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  nEventes(overrides?: CallOverrides): Promise<BigNumber>;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setAdminPermission(
    _admin: string,
    _status: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateEventResults(
    _eventIds: BigNumberish[],
    _results: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateEventStatuses(
    _eventIds: BigNumberish[],
    _status: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateSToken(
    _eventIds: BigNumberish[],
    _sToken: string[],
    _sTotal: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    createEventes(
      _descriptions: BytesLike[],
      _startTimes: BigNumberish[],
      _endTimes: BigNumberish[],
      _sToken: string[],
      _sTotal: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    eventes(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber, string, number, string, BigNumber] & {
        description: string;
        startTime: BigNumber;
        endTime: BigNumber;
        result: string;
        status: number;
        sToken: string;
        sTotal: BigNumber;
      }
    >;

    info(
      _eventId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<GDataTypes.EventStructOutput>;

    initialize(overrides?: CallOverrides): Promise<void>;

    nEventes(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setAdminPermission(
      _admin: string,
      _status: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateEventResults(
      _eventIds: BigNumberish[],
      _results: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    updateEventStatuses(
      _eventIds: BigNumberish[],
      _status: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    updateSToken(
      _eventIds: BigNumberish[],
      _sToken: string[],
      _sTotal: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "EventCreated(uint256,bytes32,uint256,uint256,address,uint256)"(
      idx?: null,
      descriptions?: null,
      startTime?: null,
      endTime?: null,
      sToken?: null,
      sTotal?: null
    ): EventCreatedEventFilter;
    EventCreated(
      idx?: null,
      descriptions?: null,
      startTime?: null,
      endTime?: null,
      sToken?: null,
      sTotal?: null
    ): EventCreatedEventFilter;

    "EventResultUpdated(address,uint256,string)"(
      caller?: null,
      eventId?: null,
      result?: null
    ): EventResultUpdatedEventFilter;
    EventResultUpdated(
      caller?: null,
      eventId?: null,
      result?: null
    ): EventResultUpdatedEventFilter;

    "EventStatusUpdated(address,uint256,uint8)"(
      caller?: null,
      eventId?: null,
      status?: null
    ): EventStatusUpdatedEventFilter;
    EventStatusUpdated(
      caller?: null,
      eventId?: null,
      status?: null
    ): EventStatusUpdatedEventFilter;

    "Initialized(uint8)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
  };

  estimateGas: {
    createEventes(
      _descriptions: BytesLike[],
      _startTimes: BigNumberish[],
      _endTimes: BigNumberish[],
      _sToken: string[],
      _sTotal: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    eventes(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    info(_eventId: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    nEventes(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setAdminPermission(
      _admin: string,
      _status: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateEventResults(
      _eventIds: BigNumberish[],
      _results: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateEventStatuses(
      _eventIds: BigNumberish[],
      _status: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateSToken(
      _eventIds: BigNumberish[],
      _sToken: string[],
      _sTotal: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createEventes(
      _descriptions: BytesLike[],
      _startTimes: BigNumberish[],
      _endTimes: BigNumberish[],
      _sToken: string[],
      _sTotal: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    eventes(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    info(
      _eventId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    nEventes(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setAdminPermission(
      _admin: string,
      _status: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateEventResults(
      _eventIds: BigNumberish[],
      _results: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateEventStatuses(
      _eventIds: BigNumberish[],
      _status: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateSToken(
      _eventIds: BigNumberish[],
      _sToken: string[],
      _sTotal: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
