/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as sponsorPredictLinkSol from "./SponsorPredictLink.sol";
export type { sponsorPredictLinkSol };
import type * as multiple from "./multiple";
export type { multiple };
export type { Greeter } from "./Greeter";
export type { SIMatchExt } from "./SIMatchExt";
export type { SponsoredMatchLink } from "./SponsoredMatchLink";
