/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20TokenSol from "./Erc20Token.sol";
export type { erc20TokenSol };
import type * as eventSol from "./Event.sol";
export type { eventSol };
import type * as linkTokenSol from "./LinkToken.sol";
export type { linkTokenSol };
import type * as custom from "./custom";
export type { custom };
export type { ChainlinkClientUpgradable } from "./ChainlinkClientUpgradable";
export type { ComPool } from "./ComPool";
export type { ELPToken } from "./ELPToken";
export type { ERC721Token } from "./ERC721Token";
export type { IEvent } from "./IEvent";
export type { IHelper } from "./IHelper";
export type { Prediction } from "./Prediction";
