/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as chainlink from "./@chainlink";
export type { chainlink };
import type * as openzeppelin from "./@openzeppelin";
export type { openzeppelin };
import type * as contracts from "./contracts";
export type { contracts };
export * as factories from "./factories";
export type { AggregatorV3Interface } from "./@chainlink/contracts/src/v0.8/interfaces/AggregatorV3Interface";
export { AggregatorV3Interface__factory } from "./factories/@chainlink/contracts/src/v0.8/interfaces/AggregatorV3Interface__factory";
export type { Ownable } from "./@openzeppelin/contracts/access/Ownable";
export { Ownable__factory } from "./factories/@openzeppelin/contracts/access/Ownable__factory";
export type { IERC20 } from "./@openzeppelin/contracts/token/ERC20/IERC20";
export { IERC20__factory } from "./factories/@openzeppelin/contracts/token/ERC20/IERC20__factory";
export type { Greeter } from "./contracts/Greeter";
export { Greeter__factory } from "./factories/contracts/Greeter__factory";
export type { MIMatch } from "./contracts/multiple/MIMatch";
export { MIMatch__factory } from "./factories/contracts/multiple/MIMatch__factory";
export type { MiniMatch } from "./contracts/multiple/MiniMatch";
export { MiniMatch__factory } from "./factories/contracts/multiple/MiniMatch__factory";
export type { MiniPrediction } from "./contracts/multiple/MiniSponsoredPredict.sol/MiniPrediction";
export { MiniPrediction__factory } from "./factories/contracts/multiple/MiniSponsoredPredict.sol/MiniPrediction__factory";
export type { SIMatchExt } from "./contracts/SIMatchExt";
export { SIMatchExt__factory } from "./factories/contracts/SIMatchExt__factory";
export type { SponsoredMatchLink } from "./contracts/SponsoredMatchLink";
export { SponsoredMatchLink__factory } from "./factories/contracts/SponsoredMatchLink__factory";
export type { SponsoredPredictionLink } from "./contracts/SponsorPredictLink.sol/SponsoredPredictionLink";
export { SponsoredPredictionLink__factory } from "./factories/contracts/SponsorPredictLink.sol/SponsoredPredictionLink__factory";
