/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  GREvent,
  GREventInterface,
} from "../../../../contracts/custom/group-predict/GREvent";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_eventId",
        type: "uint256",
      },
    ],
    name: "info",
    outputs: [
      {
        components: [
          {
            internalType: "bytes32",
            name: "description",
            type: "bytes32",
          },
          {
            internalType: "uint256",
            name: "startTime",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "endTime",
            type: "uint256",
          },
          {
            internalType: "string",
            name: "result",
            type: "string",
          },
          {
            internalType: "enum GDataTypes.EventStatus",
            name: "status",
            type: "uint8",
          },
          {
            internalType: "address",
            name: "sToken",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "sTotal",
            type: "uint256",
          },
        ],
        internalType: "struct GDataTypes.Event",
        name: "_event",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class GREvent__factory {
  static readonly abi = _abi;
  static createInterface(): GREventInterface {
    return new utils.Interface(_abi) as GREventInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): GREvent {
    return new Contract(address, _abi, signerOrProvider) as GREvent;
  }
}
