/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc20TokenSol from "./Erc20Token.sol";
export * as custom from "./custom";
export { Event__factory } from "./Event__factory";
export { IEvent__factory } from "./IEvent__factory";
export { IHelper__factory } from "./IHelper__factory";
export { Prediction__factory } from "./Prediction__factory";
